In [27]:
import tensorflow as tf
import tensorflow.compat.v2.feature_column as fc
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
test = tf.Variable([[45, 28], [27, 5], [78, 7]], tf.int32)

In [20]:
print(tf.rank(test))

tf.Tensor(2, shape=(), dtype=int32)


In [19]:
print(test.shape)

(3, 2)


In [21]:
test2 = tf.zeros([2, 3, 2, 3])
print(test2)

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]], shape=(2, 3, 2, 3), dtype=float32)


In [22]:
test3 = tf.reshape(test2, [6, -1])
print(test3)

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(6, 6), dtype=float32)


In [33]:
cars = pd.read_csv('cars.csv')
cars = cars.drop(['Unnamed: 0'], axis=1)

In [40]:
cars['year'] = cars['mfd_date'].apply(lambda x: int(x[:4]))
cars = cars[cars['mileage'] <= 500000]
cars = cars[((cars['mileage'] < 10000) & (cars['price'] > 5000)) | (cars['mileage'] > 10000)]
cars.head()

name     gearbox       fuel mfd_date  \
0  Volkswagen Passat, 2.0 l., universalas  Automatinė  Dyzelinas  2018-12   
1  Volkswagen Passat, 1.9 l., universalas   Mechaninė  Dyzelinas  2002-11   
2  Volkswagen Passat, 2.0 l., universalas   Mechaninė  Dyzelinas  2006-12   
3  Volkswagen Passat, 2.0 l., universalas   Mechaninė  Dyzelinas  2009-04   
4  Volkswagen Passat, 2.0 l., universalas  Automatinė  Dyzelinas  2007-11   

   mileage  power  price  year  
0    18000    110  16999  2018  
1   295100     74   1400  2002  
2   260800    103   3000  2006  
3   297340    103   2700  2009  
4   271200    103   2999  2007

In [41]:
features = cars[['mileage', 'power', 'year', 'gearbox']]
prices = cars['price']

In [43]:
X_train, X_test, y_train, y_test = train_test_split(features, prices, test_size=0.2, random_state=1)

In [47]:
categorical_columns = ['gearbox']
numeric_columns = ['mileage', 'power', 'year']

feature_columns = []
for feature_name in categorical_columns:
    vocabulary = X_train[feature_name].unique()
    feature_columns.append(tf.feature_column.categorical_column_with_vocabulary_list(feature_name, vocabulary))

for feature_name in numeric_columns:
    feature_columns.append(tf.feature_column.numeric_column(feature_name, dtype=tf.int32))